[project]
name = "pyscripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "git-filter-repo>=2.47.0",
    "requests>=2.32.5",
]
